import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cloudflareDir = path.join(root, 'cloudflare');

function run(command) {
  return execSync(command, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}

function parseNamespaceId(output) {
  const jsonMatch = output.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      if (parsed.id) return parsed.id;
    } catch { /* Fall through to the wrangler text format. */ }
  }
  const idMatch = output.match(/id\s*=\s*"([^"]+)"/) || output.match(/\bid\b["':\s]+([a-f0-9]{32})/i);
  if (!idMatch) throw new Error(`Could not find a KV namespace id in:\n${output}`);
  return idMatch[1];
}

const listOutput = run('npx wrangler kv namespace list');
let namespaces = [];
try { namespaces = JSON.parse(listOutput); }
catch {
  throw new Error(`wrangler kv namespace list did not return JSON:\n${listOutput}`);
}

let namespace = namespaces.find((item) => item.title === 'color-pop-houses');
if (!namespace) {
  const created = run('npx wrangler kv namespace create color-pop-houses');
  namespace = { id: parseNamespaceId(created), title: 'color-pop-houses' };
}

writeFileSync(path.join(cloudflareDir, 'wrangler.generated.toml'), `# Generated by scripts/deploy-api.mjs
name = "color-pop-api"
main = "worker.js"
compatibility_date = "2025-04-01"
workers_dev = true

[[kv_namespaces]]
binding = "HOUSES"
id = "${namespace.id}"
`);

process.stdout.write(run(`npx wrangler deploy --config ${path.join(cloudflareDir, 'wrangler.generated.toml')}\n`));
